#!/usr/bin/env python3
"""Regenerate THIRD_PARTY_NOTICES.md from each skill's metadata.sources and the registry below.

Usage: python3 scripts/build_notices.py [--check]
Fails if a skill cites an upstream repo that is not in UPSTREAMS, so every new source must be
license-checked and registered before it can be cited.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "THIRD_PARTY_NOTICES.md"

# repo -> (commit read, SPDX, copyright line, license file under licenses/)
UPSTREAMS = {
    "addyosmani/agent-skills": ("2686b62", "MIT", "Copyright (c) 2025 Addy Osmani", "MIT-addyosmani-agent-skills.txt"),
    "addyosmani/web-quality-skills": ("afa8da9", "MIT", "Copyright (c) 2026 Addy Osmani", "MIT-addyosmani-web-quality-skills.txt"),
    "mattpocock/skills": ("c55ee46", "MIT", "Copyright (c) 2026 Matt Pocock", "MIT-mattpocock-skills.txt"),
    "obra/superpowers": ("8ca22db", "MIT", "Copyright (c) 2025 Jesse Vincent", "MIT-obra-superpowers.txt"),
    "garrytan/gstack": ("01593aa", "MIT", "Copyright (c) 2026 Garry Tan", "MIT-garrytan-gstack.txt"),
    "wshobson/agents": ("9b15b34", "MIT", "Copyright (c) 2024 Seth Hobson", "MIT-wshobson-agents.txt"),
    "supabase/agent-skills": ("551274e", "MIT", "Copyright (c) 2026 Supabase", "MIT-supabase-agent-skills.txt"),
    "LukasNiessen/terrashark": ("21f2c18", "MIT", "Copyright 2025 Lukas Niessen", "MIT-LukasNiessen-terrashark.txt"),
    "levnikolaevich/claude-code-skills": ("d7da390", "MIT", "Copyright (c) 2026 Lev Nikolaevich", "MIT-levnikolaevich-claude-code-skills.txt"),
    "muratcankoylan/Agent-Skills-for-Context-Engineering": ("6dbe1a1", "MIT", "Copyright (c) 2025 Context Engineering Agent Skills Contributors", "MIT-muratcankoylan-Agent-Skills-for-Context-Engineering.txt"),
    "getsentry/skills": ("c2f99a5", "Apache-2.0", "Sentry (LICENSE has no copyright line)", "Apache-2.0.txt"),
    "anthropics/claude-plugins-official": ("fa59bc9", "Apache-2.0", "Anthropic, PBC (LICENSE has no copyright line)", "Apache-2.0.txt"),
    "anthropics/skills": ("3337550", "Apache-2.0 (per-skill LICENSE.txt; only Apache-2.0 skills used)", "Anthropic, PBC", "Apache-2.0.txt"),
    "openai/skills": ("49f948f", "Apache-2.0 (per-skill LICENSE.txt; only Apache-2.0 skills used)", "OpenAI", "Apache-2.0.txt"),
}

# Copyleft, custom-licensed or unlicensed repos: cited as "ideas: owner/repo" only, never as text sources.
IDEAS_ONLY = {
    "trailofbits/skills": "CC-BY-SA-4.0",
    "NeoLabHQ/context-engineering-kit": "GPL-3.0",
    "hashicorp/agent-skills": "MPL-2.0",
    "antonbabenko/terraform-skill": "custom license",
    "vercel-labs/agent-skills": "no LICENSE file",
}

SOURCES_RE = re.compile(r'^  sources: "(.*)"$', re.M)
ENTRY_RE = re.compile(r"(ideas:\s*)?([A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+)")

HEADER = """# Third-party notices

Every skill in `skills/` was written for this repository. Each one synthesizes techniques from the open-source collections below: reworded, restructured and extended, not copied. An 8-word-sequence overlap check against all upstream skills shows 0–2.5% shared phrasing per skill. The shared phrases are generic wording, WCAG criterion names, or standard tool syntax.

The ideas and structure still come from these projects, and their authors deserve the credit. Each skill's `metadata.sources` field names the exact upstream skills it draws on. Listing a project here does not imply its authors endorse this work.

This file is generated by `scripts/build_notices.py`; edit the registry there.
"""

FOOTER = """
## Not used

These were reviewed and deliberately excluded because their licenses do not allow reuse:
- Anthropic's docx, pdf, pptx and xlsx skills and `claude-security` (proprietary);
- openai/skills `figma*` (Figma Developer Terms);
- ykdojo/claude-code-tips (all rights reserved);
- hesreallyhim/awesome-claude-code (CC BY-NC-ND);
- dpearson2699/swift-ios-skills (PolyForm);
- Semgrep and Databricks skills (non-OSI licenses);
- any repo without a LICENSE file.

None of the Apache-2.0 upstreams used ships a NOTICE file that would need reproducing.
"""


def collect():
    text_uses, idea_uses, unknown = {}, {}, []
    for skill_md in sorted((ROOT / "skills").glob("*/SKILL.md")):
        name = skill_md.parent.name
        match = SOURCES_RE.search(skill_md.read_text(encoding="utf-8"))
        if not match:
            continue
        for part in match.group(1).split(";"):
            part = part.strip()
            if not part or part == "original":
                continue
            is_idea = part.startswith("ideas:") or part.startswith("original; ideas:")
            for idea_prefix, repo in ENTRY_RE.findall(part):
                if repo not in UPSTREAMS and repo not in IDEAS_ONLY:
                    if "/" in repo and not re.match(r"^[A-Z][a-z]+/[A-Z]", repo):
                        unknown.append(f"{name}: {repo}")
                    continue
                if repo in IDEAS_ONLY or is_idea or idea_prefix:
                    idea_uses.setdefault(repo, set()).add(name)
                else:
                    text_uses.setdefault(repo, set()).add(name)
    bad = [f"{s}: {r}" for r, skills in text_uses.items() if r in IDEAS_ONLY for s in skills]
    return text_uses, idea_uses, unknown, bad


def render(text_uses, idea_uses):
    lines = [HEADER, "## Sources\n", "| Upstream | Commit read | License | Copyright | Used by |", "|---|---|---|---|---|"]
    for repo in sorted(text_uses, key=lambda r: (-len(text_uses[r]), r.lower())):
        commit, spdx, holder, _ = UPSTREAMS[repo]
        users = ", ".join(sorted(text_uses[repo]))
        lines.append(f"| [{repo}](https://github.com/{repo}) | `{commit}` | {spdx} | {holder} | {users} |")
    lines += ["", "### Ideas only, no text", "",
              "General ideas taken from these repositories were reworded from scratch. No text, structure or code was adapted, so copyleft or restrictive terms do not attach.", "",
              "| Upstream | License | Used by |", "|---|---|---|"]
    for repo in sorted(idea_uses, key=str.lower):
        license_name = IDEAS_ONLY.get(repo) or UPSTREAMS[repo][1]
        lines.append(f"| [{repo}](https://github.com/{repo}) | {license_name} | {', '.join(sorted(idea_uses[repo]))} |")
    files = sorted({UPSTREAMS[r][3] for r in text_uses})
    lines += ["", "## License texts", ""] + [f"- [licenses/{f}](licenses/{f})" for f in files]
    return "\n".join(lines) + "\n" + FOOTER


def main():
    text_uses, idea_uses, unknown, bad = collect()
    if unknown or bad:
        for item in unknown:
            print(f"unregistered upstream (license-check it, then add to UPSTREAMS or IDEAS_ONLY): {item}")
        for item in bad:
            print(f"ideas-only repo cited as a text source (prefix it with 'ideas:'): {item}")
        sys.exit(1)
    for repo in text_uses:
        if not (ROOT / "licenses" / UPSTREAMS[repo][3]).is_file():
            sys.exit(f"missing license file licenses/{UPSTREAMS[repo][3]} for {repo}")
    rendered = render(text_uses, idea_uses)
    if "--check" in sys.argv[1:]:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != rendered:
            print("THIRD_PARTY_NOTICES.md is stale; run: python3 scripts/build_notices.py")
            sys.exit(1)
        print("THIRD_PARTY_NOTICES.md is up to date")
        return
    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(text_uses)} text sources, {len(idea_uses)} idea-only sources")


if __name__ == "__main__":
    main()
